/**
 * WORLD — Bengaluru palette overrides.
 *
 * Remaps the shared palette keys that `buildings.js`, `kit.js` and
 * `dressing.js` name onto the Indian surface set, so the same geometry renders
 * as a Bengaluru street. See `setPaletteOverrides` in ../../palette.js.
 *
 * THE THREE MOVES THAT DO THE WORK
 *
 * 1. WALLS BECOME PAINTED, NOT RENDERED. Desert stucco is the colour of the
 *    sand it is made from. An Indian wall is cement render with distemper or
 *    emulsion over it, in a colour someone chose — pale blue, ochre, pink,
 *    lime. `plaster_painted` bakes near-white so the per-key `tint` (a linear
 *    multiply) can carry the colour; multiply can only darken, which is why the
 *    bake is light.
 *
 * 2. EVERYTHING RUNS WET. `weather` is [dust, streak, splashHeight, cavity].
 *    The market street runs streak 0.5; every key here runs 0.85-1.0 with a
 *    green-black `grimeColor`. Bengaluru takes ~970 mm of rain a year and the
 *    single most recognisable thing about its buildings is the black tail
 *    running down from every chajja, sill and drainpipe bracket. That streak is
 *    generated by shader.js off world Y, so it costs nothing here but a number.
 *
 * 3. CANOPIES BECOME TARPAULIN. The market stalls' striped cloth becomes blue
 *    and orange poly tarp. Structurally the same awning; completely different
 *    country.
 */

/** Shared weathering profile: heavy monsoon streaking, high ground splash. */
const WET = [0.35, 0.9, 0.75, 0.6];
const WET_LIGHT = [0.3, 0.75, 0.6, 0.55];

/** Algae-black, not soot-black — this is the colour of the streaks. */
const ALGAE = 0x141a0e;
const DAMP_DUST = 0x7f7a68;

const wall = (tint, scale, weather = WET) => ({
  name: 'plaster_painted',
  surface: 'plaster',
  opts: {
    vertexMasks: true,
    tint,
    scale,
    weather,
    grimeColor: ALGAE,
    dustColor: DAMP_DUST,
  },
});

export const BENGALURU_PALETTE = {
  // ------------------------------------------------------------ walls -----
  // Colours off actual Bengaluru streets: lime-washed cream, ochre, the pale
  // "hospital blue" that is on every second building, faded rose, and white.
  plaster_cream: wall(0xd6c9a8, 2.35),
  plaster_sand: wall(0xc4a878, 2.1),
  plaster_blue: wall(0x93b4c4, 2.2),
  plaster_pink: wall(0xd0a094, 2.5),
  plaster_white: wall(0xe0dccf, 1.9, WET_LIGHT),

  // ----------------------------------------------------------- concrete ---
  // Plinths, compound walls, kerbs, drain slabs, unfinished RCC. Damp and
  // colonised rather than dry and dusty.
  concrete: {
    name: 'moss_concrete',
    surface: 'concrete',
    opts: {
      vertexMasks: true,
      tint: 0xa9a49a,
      scale: 2.5,
      weather: WET,
      grimeColor: ALGAE,
      dustColor: DAMP_DUST,
    },
  },
  concrete_dark: {
    name: 'moss_concrete',
    surface: 'concrete',
    opts: {
      vertexMasks: true,
      tint: 0x6f6d67,
      scale: 2.2,
      weather: WET,
      grimeColor: ALGAE,
      dustColor: DAMP_DUST,
    },
  },

  // ------------------------------------------------------------ canopies --
  // The market stalls and awnings. `three.side: 2` is carried over because
  // these are single-sided cloth grids seen from underneath.
  fabric_teal: {
    name: 'tarpaulin',
    surface: 'fabric',
    opts: { vertexMasks: true, scale: 0.5, three: { side: 2 } },
  },
  fabric_red: {
    name: 'tarpaulin_orange',
    surface: 'fabric',
    opts: { vertexMasks: true, scale: 0.5, three: { side: 2 } },
  },
  // Left as cloth on purpose: a street where every single canopy is a poly tarp
  // reads as a refugee camp. Cotton awnings and drying saris need to survive.
  // fabric_cream — unchanged.

  // ======================================================== street ========
  // NEW keys, not overrides — `paletteOf` checks this table first, so a level
  // can introduce keys the base palette has never heard of. Used by street.js.

  /** Resurfacing patch: newer, blacker tar than the road around it. */
  road_patch: {
    name: 'asphalt',
    surface: 'concrete',
    opts: { vertexMasks: true, tint: 0x6d6a66, scale: 1.6, weather: [0.3, 0.2, 0, 0.5] },
  },
  /** Speed-breaker arc — same asphalt as the road, worn on the crown. */
  road_hump: {
    name: 'asphalt',
    surface: 'concrete',
    opts: { vertexMasks: true, tint: 0x8a8580, scale: 1.8, weather: [0.35, 0.2, 0, 0.55] },
  },

  // Road paint is never clean. `tint` is a linear multiply so it can only
  // darken the baked albedo — which is correct here, since corporation paint
  // is chalky and immediately filthy. Nothing on this street is a pure value.
  paint_white: {
    name: 'concrete',
    surface: 'concrete',
    opts: { vertexMasks: true, tint: 0xe8e4d8, scale: 0.5, weather: [0.5, 0.3, 0, 0.6] },
  },
  paint_yellow: {
    name: 'concrete',
    surface: 'concrete',
    opts: { vertexMasks: true, tint: 0xe0b038, scale: 0.5, weather: [0.5, 0.35, 0, 0.6] },
  },
  paint_black: {
    name: 'concrete',
    surface: 'concrete',
    opts: { vertexMasks: true, tint: 0x2e2c28, scale: 0.5, weather: [0.4, 0.3, 0, 0.6] },
  },

  /** Storm-drain lid: precast concrete, wet, algae in every joint. */
  drain_slab: {
    name: 'moss_concrete',
    surface: 'concrete',
    opts: {
      vertexMasks: true,
      tint: 0x8e8b84,
      scale: 1.1,
      weather: WET,
      grimeColor: ALGAE,
      dustColor: DAMP_DUST,
    },
  },
  // ======================================================= landmark =======
  // Vidhana Soudha. Bengaluru is granite country and the building is faced in
  // it — warm grey-cream, coarse, and it takes pollution in the crevices.
  granite: {
    name: 'concrete',
    surface: 'concrete',
    opts: {
      vertexMasks: true,
      tint: 0xc9bda4,
      scale: 3.4,
      weather: [0.4, 0.7, 1.6, 0.6],
      grimeColor: ALGAE,
      dustColor: DAMP_DUST,
      roughness: [0.95, -0.02, 0.26],
    },
  },
  granite_dark: {
    name: 'concrete',
    surface: 'concrete',
    opts: {
      vertexMasks: true,
      tint: 0x8d8674,
      scale: 2.2,
      weather: [0.4, 0.8, 1.2, 0.65],
      grimeColor: ALGAE,
      dustColor: DAMP_DUST,
    },
  },

  // ========================================================== props =======
  // Used by props.js.

  /**
   * The white monobloc chair and the foil sachet strips. Injection-moulded
   * polypropylene: near-white, low roughness, and it goes grey-brown at every
   * contact point rather than rusting or rotting.
   */
  plastic_white: {
    name: 'plaster',
    surface: 'plaster',
    opts: {
      vertexMasks: true,
      tint: 0xd8d5cc,
      scale: 0.4,
      weather: [0.45, 0.4, 0.3, 0.7],
      grimeColor: ALGAE,
      roughness: [0.7, -0.02, 0.3],
    },
  },
  /** Milk crates — saturated moulded plastic, scuffed pale on every edge. */
  plastic_crate: {
    name: 'rubber',
    surface: 'rubber',
    opts: { vertexMasks: true, tint: 0x8f5a48, scale: 0.3, weather: [0.4, 0.4, 0.3, 0.6] },
  },

  // ======================================================= vehicles =======
  // Used by vehicles.js. The two-tone IS the Bengaluru auto, so these are two
  // keys and two draw calls rather than one compromise material.

  /**
   * Auto body: black enamel over steel.
   *
   * The tint has to go a long way down. `metal_painted` bakes a mid olive and
   * carries a pale `wearColor` (0x8f9296) that the curvature/edge-wear term
   * lifts toward — on a shape with as many chamfers as a vehicle that is most
   * of the surface, so a "dark grey" tint lands as light grey. Black enamel is
   * ~0.04 reflectance; going to 0x1a1a1d gets it there and lets the edge wear
   * read as chipped paint rather than as the base colour.
   */
  auto_black: {
    name: 'metal_painted',
    surface: 'metal',
    opts: {
      vertexMasks: true,
      tint: 0x1a1a1d,
      scale: 0.6,
      weather: [0.35, 0.4, 0.35, 0.6],
      wearColor: 0x6a6055,
      roughness: [0.85, -0.03, 0.3],
    },
  },
  /**
   * Auto canopy: yellow canvas/vinyl, sun-bleached on the crown.
   *
   * Points at the YELLOW tarpaulin bake, not at the blue one with a yellow
   * tint — `tint` multiplies the baked albedo, so blue x yellow renders green.
   */
  auto_yellow: {
    name: 'tarpaulin_yellow',
    surface: 'fabric',
    opts: {
      vertexMasks: true,
      scale: 0.35,
      weather: [0.4, 0.4, 0.2, 0.5],
      three: { side: 2 },
    },
  },

  // ======================================================== facade ========
  // Used by facade.js.

  /** Sintex water tank — black three-layer polyethylene, chalked by UV. */
  tank_black: {
    name: 'rubber',
    surface: 'rubber',
    opts: { vertexMasks: true, tint: 0x4a4640, scale: 0.7, weather: [0.5, 0.5, 0, 0.5] },
  },
  /** The pale-blue tank, the other one you see on every roof. */
  tank_blue: {
    name: 'rubber',
    surface: 'rubber',
    opts: { vertexMasks: true, tint: 0x7f9dad, scale: 0.7, weather: [0.5, 0.5, 0, 0.5] },
  },
  /** UPVC plumbing. Everything on an Indian roof is connected by this. */
  pvc_pipe: {
    name: 'plaster',
    surface: 'plaster',
    opts: { vertexMasks: true, tint: 0x9aa0a4, scale: 0.35, weather: [0.4, 0.5, 0, 0.5] },
  },

  // Rolling shutters. Painted steel, and the colour is a real signal: shutters
  // are almost always one of a small set of cheap enamels.
  shutter_blue: {
    name: 'metal_painted',
    surface: 'metal',
    opts: { vertexMasks: true, tint: 0x5d7f96, scale: 0.55, weather: [0.35, 0.7, 0.4, 0.55] },
  },
  shutter_green: {
    name: 'metal_painted',
    surface: 'metal',
    opts: { vertexMasks: true, tint: 0x5e7a5c, scale: 0.55, weather: [0.35, 0.7, 0.4, 0.55] },
  },
  shutter_grey: {
    name: 'metal_painted',
    surface: 'metal',
    opts: { vertexMasks: true, tint: 0x8a8880, scale: 0.55, weather: [0.35, 0.7, 0.4, 0.55] },
  },

  /** The trench where a lid is missing. Dark, wet, and you do not want to look. */
  drain_void: {
    name: 'moss_concrete',
    surface: 'concrete',
    opts: {
      vertexMasks: true,
      tint: 0x24261e,
      scale: 1.0,
      weather: [0.1, 0.4, 0, 0.9],
      grimeColor: ALGAE,
    },
  },
};
